use bytes::Bytes;
use jolyne::batch::{decode_batch_raw, encode_batch_multi};
use jolyne::valentine::{McpePacketArgs, McpePacketData, RecipesItemRecipe, RecipesItemType};
use protocol::BedrockSession;

// Generated by pinned gophertunnel protocol 1001 from a one-cell shaped
// recipe. Shaped inputs are exactly width*height descriptors and carry no
// outer or row length prefixes.
// SHA-256: 33c86d633237c5da6fc59fc12de3e6cd5c01dddf9734326a20fe79f8ef6a2f73
const GOPHERTUNNEL_ONE_CELL_SHAPED_RECIPE: &[u8] = &[
    0xfe, 0x33, 0xb4, 0x48, 0x01, 0x02, 0x01, 0x78, 0x02, 0x02, 0x00, 0x02, 0x01, 0x01, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0e, 0x63,
    0x72, 0x61, 0x66, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x00, 0x00, 0x01,
    0x07, 0x00, 0x00, 0x00, 0x00,
];

fn raw_crafting_data() -> jolyne::raw::RawPacket {
    let mut batch = Bytes::from_static(GOPHERTUNNEL_ONE_CELL_SHAPED_RECIPE);
    decode_batch_raw(&mut batch, false, Some(1024))
        .expect("raw batch decode")
        .into_iter()
        .next()
        .expect("one packet")
}

fn assert_one_cell_shaped_recipe(data: &McpePacketData) {
    let McpePacketData::PacketCraftingData(packet) = data else {
        panic!("expected CraftingData, got {:?}", data.packet_id());
    };
    assert_eq!(packet.recipes.len(), 1);
    assert_eq!(packet.recipes[0].type_, RecipesItemType::Shaped);
    let Some(RecipesItemRecipe::Shaped(recipe)) = &packet.recipes[0].recipe else {
        panic!("expected shaped recipe payload");
    };
    assert_eq!((recipe.width, recipe.height), (1, 1));
    assert_eq!(recipe.input.len(), 1);
    assert_eq!(recipe.output.len(), 1);
    assert_eq!(recipe.block, "crafting_table");
}

#[test]
fn pinned_gophertunnel_shaped_recipe_owned_decodes_and_round_trips_exactly() {
    let packet = raw_crafting_data()
        .decode(&BedrockSession { shield_item_id: 0 })
        .expect("owned CraftingData decode");
    assert_one_cell_shaped_recipe(&packet.data);
    let encoded = encode_batch_multi(&[packet], false, 0, 0, true).expect("re-encode");
    assert_eq!(encoded.as_ref(), GOPHERTUNNEL_ONE_CELL_SHAPED_RECIPE);
}

#[test]
fn pinned_gophertunnel_shaped_recipe_borrowed_materializes() {
    let borrowed = raw_crafting_data()
        .decode_borrowed()
        .expect("borrowed CraftingData decode");
    let owned = borrowed
        .data
        .into_owned(McpePacketArgs { shield_item_id: 0 })
        .expect("materialize borrowed CraftingData");
    assert_one_cell_shaped_recipe(&owned);
}

#[test]
fn shaped_recipe_rejects_negative_dimensions_even_when_product_is_positive() {
    let mut packet = raw_crafting_data()
        .decode(&BedrockSession { shield_item_id: 0 })
        .expect("owned CraftingData decode");
    let McpePacketData::PacketCraftingData(content) = &mut packet.data else {
        panic!("expected CraftingData");
    };
    let Some(RecipesItemRecipe::Shaped(recipe)) = &mut content.recipes[0].recipe else {
        panic!("expected shaped recipe payload");
    };
    recipe.width = -1;
    recipe.height = -1;

    encode_batch_multi(&[packet], false, 0, 0, true)
        .expect_err("negative shaped-recipe dimensions must fail encoding");
}
