use bytes::Bytes;
use jolyne::batch::{decode_batch_raw, encode_batch_multi};
use jolyne::valentine::{McpePacketArgs, McpePacketData};
use protocol::BedrockSession;

// Generated by pinned gophertunnel protocol 1001 from one anonymous creative
// group whose icon is the legacy empty sentinel (network ID -1), and no items.
// SHA-256: e6320ead1d619d075b7519f366815baec98b258a5b09bf3d217b8269bc365102
const GOPHERTUNNEL_EMPTY_ICON_CREATIVE_CONTENT: &[u8] = &[
    0xfe, 0x0a, 0x91, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00,
];

// Generated from the exact enchanted-book creative group emitted by the live
// protocol-1001 BDS session and independently decoded by pinned gophertunnel.
// The icon carries fixed-width little-endian item NBT.
// SHA-256: 85e3f7083ae524ebe7f14b09da5f99d0e132cd2d5fe2d49d4cc23b06969a2d41
const GOPHERTUNNEL_ENCHANTED_BOOK_CREATIVE_CONTENT: &[u8] = &[
    0xfe, 0x57, 0x91, 0x01, 0x01, 0x04, 0x00, 0x00, 0x00, 0x1c, 0x69, 0x74, 0x65, 0x6d, 0x47, 0x72,
    0x6f, 0x75, 0x70, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74,
    0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0xe0, 0x08, 0x01, 0x00, 0x00, 0x00, 0x2b, 0xff, 0xff, 0x01,
    0x0a, 0x00, 0x00, 0x09, 0x04, 0x00, 0x65, 0x6e, 0x63, 0x68, 0x0a, 0x01, 0x00, 0x00, 0x00, 0x02,
    0x02, 0x00, 0x69, 0x64, 0x00, 0x00, 0x02, 0x03, 0x00, 0x6c, 0x76, 0x6c, 0x01, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

fn raw_creative_content() -> jolyne::raw::RawPacket {
    raw_creative_content_fixture(GOPHERTUNNEL_EMPTY_ICON_CREATIVE_CONTENT)
}

fn raw_creative_content_fixture(fixture: &'static [u8]) -> jolyne::raw::RawPacket {
    let mut batch = Bytes::from_static(fixture);
    decode_batch_raw(&mut batch, false, Some(1024))
        .expect("raw batch decode")
        .into_iter()
        .next()
        .expect("one packet")
}

#[test]
fn pinned_gophertunnel_enchanted_book_nbt_decodes_and_round_trips_exactly() {
    let packet = raw_creative_content_fixture(GOPHERTUNNEL_ENCHANTED_BOOK_CREATIVE_CONTENT)
        .decode(&BedrockSession { shield_item_id: 0 })
        .expect("owned enchanted-book CreativeContent decode");
    let McpePacketData::PacketCreativeContent(content) = &packet.data else {
        panic!(
            "expected CreativeContent, got {:?}",
            packet.data.packet_id()
        );
    };
    assert_eq!(content.groups.len(), 1);
    assert_eq!(content.groups[0].name, "itemGroup.name.enchantedBook");
    assert_eq!(content.groups[0].icon_item.network_id, 560);
    assert!(content.groups[0].icon_item.content.is_some());
    assert!(content.items.is_empty());

    let encoded = encode_batch_multi(&[packet], false, 0, 0, true).expect("re-encode");
    assert_eq!(
        encoded.as_ref(),
        GOPHERTUNNEL_ENCHANTED_BOOK_CREATIVE_CONTENT
    );
}

#[test]
fn pinned_gophertunnel_enchanted_book_nbt_borrowed_materializes() {
    let borrowed = raw_creative_content_fixture(GOPHERTUNNEL_ENCHANTED_BOOK_CREATIVE_CONTENT)
        .decode_borrowed()
        .expect("borrowed enchanted-book CreativeContent decode");
    let owned = borrowed
        .data
        .into_owned(McpePacketArgs { shield_item_id: 0 })
        .expect("materialize borrowed enchanted-book CreativeContent");
    let McpePacketData::PacketCreativeContent(content) = owned else {
        panic!("expected CreativeContent");
    };
    assert_eq!(content.groups.len(), 1);
    assert_eq!(content.groups[0].icon_item.network_id, 560);
}

fn assert_empty_icon_payload(data: &McpePacketData) {
    let McpePacketData::PacketCreativeContent(packet) = data else {
        panic!("expected CreativeContent, got {:?}", data.packet_id());
    };
    assert_eq!(packet.groups.len(), 1);
    assert_eq!(packet.groups[0].icon_item.network_id, -1);
    assert!(packet.groups[0].icon_item.content.is_none());
    assert!(packet.items.is_empty());
}

#[test]
fn pinned_gophertunnel_empty_icon_decodes_and_round_trips_exactly() {
    let packet = raw_creative_content()
        .decode(&BedrockSession { shield_item_id: 0 })
        .expect("owned CreativeContent decode");
    assert_empty_icon_payload(&packet.data);
    let encoded = encode_batch_multi(&[packet], false, 0, 0, true).expect("re-encode");
    assert_eq!(encoded.as_ref(), GOPHERTUNNEL_EMPTY_ICON_CREATIVE_CONTENT);
}

#[test]
fn pinned_gophertunnel_empty_icon_borrowed_materializes_without_content() {
    let borrowed = raw_creative_content()
        .decode_borrowed()
        .expect("borrowed CreativeContent decode");
    let owned = borrowed
        .data
        .into_owned(McpePacketArgs { shield_item_id: 0 })
        .expect("materialize borrowed CreativeContent");
    assert_empty_icon_payload(&owned);
}
