use bytes::{Bytes, BytesMut};
use jolyne::batch::{decode_batch_raw, encode_batch_multi};
use jolyne::valentine::{
    McpePacketArgs, McpePacketData, PlayerRecords, PlayerRecordsRecordsItem,
    PlayerRecordsRecordsItemAdd, PlayerRecordsRecordsItemRemove, PlayerRecordsType,
    bedrock::{
        codec::{BedrockCodec, VarInt},
        error::DecodeError,
    },
};
use protocol::BedrockSession;

// Generated by the pinned gophertunnel protocol 1001 encoder from:
// PlayerList{ActionType: Remove, Entries: [{UUID:
// 01020304-0506-0708-090a-0b0c0d0e0f10}]}.
// SHA-256: 1c1432f38e374b2fa44263140d7b0aba1d64b685e4566a4bca5a541ad903c0bb
const GOPHERTUNNEL_PLAYER_LIST_REMOVE: &[u8] = &[
    0xfe, 0x13, 0x3f, 0x01, 0x01, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x10, 0x0f, 0x0e,
    0x0d, 0x0c, 0x0b, 0x0a, 0x09,
];

// Generated by the pinned gophertunnel protocol 1001 encoder from one minimal
// Add entry whose skin is trusted. The final byte is the one trusted-skin bool
// associated with the shared entry count; it has no second count prefix.
// SHA-256: 3beb026f11d8b29742c6e96e14b7fd1f9832bd5bf6b7da38715a5dfd7ae211dd
const GOPHERTUNNEL_PLAYER_LIST_ADD: &[u8] = &[
    0xfe, 0x58, 0xbf, 0x48, 0x00, 0x01, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x10, 0x0f,
    0x0e, 0x0d, 0x0c, 0x0b, 0x0a, 0x09, 0x02, 0x07, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
];

fn raw_player_list() -> jolyne::raw::RawPacket {
    raw_player_list_fixture(GOPHERTUNNEL_PLAYER_LIST_REMOVE)
}

fn raw_player_list_fixture(fixture: &'static [u8]) -> jolyne::raw::RawPacket {
    let mut batch = Bytes::from_static(fixture);
    decode_batch_raw(&mut batch, false, Some(1024))
        .expect("raw batch decode")
        .into_iter()
        .next()
        .expect("one packet")
}

#[test]
fn pinned_gophertunnel_player_list_add_uses_shared_count_for_verified_flags() {
    let packet = raw_player_list_fixture(GOPHERTUNNEL_PLAYER_LIST_ADD)
        .decode(&BedrockSession { shield_item_id: 0 })
        .expect("owned Add PlayerList decode");
    let McpePacketData::PacketPlayerList(content) = &packet.data else {
        panic!("expected PlayerList");
    };
    assert_eq!(content.records.type_, PlayerRecordsType::Add);
    assert_eq!(content.records.records_count, 1);
    assert!(matches!(
        content.records.records.as_slice(),
        [Some(PlayerRecordsRecordsItem::Add(_))]
    ));
    assert_eq!(content.records.verified.as_deref(), Some(&[true][..]));

    let encoded = encode_batch_multi(&[packet], false, 0, 0, true).expect("re-encode");
    assert_eq!(encoded.as_ref(), GOPHERTUNNEL_PLAYER_LIST_ADD);
}

fn assert_remove_payload(data: &McpePacketData) {
    let McpePacketData::PacketPlayerList(packet) = data else {
        panic!("expected PlayerList, got {:?}", data.packet_id());
    };
    assert_eq!(packet.records.type_, PlayerRecordsType::Remove);
    assert_eq!(packet.records.records_count, 1);
    assert_eq!(packet.records.records.len(), 1);
    assert!(packet.records.verified.is_none());
    assert!(matches!(
        packet.records.records[0],
        Some(PlayerRecordsRecordsItem::Remove(_))
    ));
}

#[test]
fn pinned_gophertunnel_player_list_owned_decodes_and_round_trips_exactly() {
    let packet = raw_player_list()
        .decode(&BedrockSession { shield_item_id: 0 })
        .expect("owned PlayerList decode");
    assert_remove_payload(&packet.data);
    let encoded = encode_batch_multi(&[packet], false, 0, 0, true).expect("re-encode");
    assert_eq!(encoded.as_ref(), GOPHERTUNNEL_PLAYER_LIST_REMOVE);
}

#[test]
fn pinned_gophertunnel_player_list_borrowed_materializes_with_same_count() {
    let borrowed = raw_player_list()
        .decode_borrowed()
        .expect("borrowed PlayerList decode");
    let owned = borrowed
        .data
        .into_owned(McpePacketArgs { shield_item_id: 0 })
        .expect("materialize borrowed PlayerList");
    assert_remove_payload(&owned);
}

fn encoded_player_records(records: &PlayerRecords) -> Result<BytesMut, std::io::Error> {
    let mut encoded = BytesMut::new();
    records.encode(&mut encoded)?;
    Ok(encoded)
}

fn remove_record() -> Option<PlayerRecordsRecordsItem> {
    Some(PlayerRecordsRecordsItem::Remove(
        PlayerRecordsRecordsItemRemove::default(),
    ))
}

fn add_record() -> Option<PlayerRecordsRecordsItem> {
    Some(PlayerRecordsRecordsItem::Add(Box::new(
        PlayerRecordsRecordsItemAdd::default(),
    )))
}

#[test]
fn player_records_decode_rejects_count_above_gophertunnel_slice_limit() {
    let mut encoded = BytesMut::new();
    PlayerRecordsType::Remove
        .encode(&mut encoded)
        .expect("action type");
    VarInt(4097).encode(&mut encoded).expect("record count");
    encoded.extend_from_slice(&vec![0; 4097]);

    let error = PlayerRecords::decode(&mut encoded.freeze(), ()).expect_err("oversized count");
    assert!(matches!(
        error,
        DecodeError::ArrayLengthExceeded {
            declared: 4097,
            available: 4096,
        }
    ));
}

#[test]
fn player_records_decode_rejects_count_larger_than_remaining_bytes() {
    let mut encoded = BytesMut::new();
    PlayerRecordsType::Remove
        .encode(&mut encoded)
        .expect("action type");
    VarInt(2).encode(&mut encoded).expect("record count");

    let error = PlayerRecords::decode(&mut encoded.freeze(), ()).expect_err("truncated records");
    assert!(matches!(
        error,
        DecodeError::ArrayLengthExceeded {
            declared: 2,
            available: 0,
        }
    ));
}

#[test]
fn player_records_encode_rejects_count_and_record_length_mismatch_before_writing() {
    let records = PlayerRecords {
        type_: PlayerRecordsType::Remove,
        records_count: 2,
        records: vec![remove_record()],
        verified: None,
    };
    let mut encoded = BytesMut::new();

    let error = records
        .encode(&mut encoded)
        .expect_err("inconsistent count");
    assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);
    assert!(encoded.is_empty(), "validation must precede all writes");
}

#[test]
fn player_records_encode_rejects_action_record_mismatch() {
    let records = PlayerRecords {
        type_: PlayerRecordsType::Add,
        records_count: 1,
        records: vec![remove_record()],
        verified: Some(vec![true]),
    };

    let error = encoded_player_records(&records).expect_err("mismatched record variant");
    assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);
}

#[test]
fn player_records_encode_rejects_missing_or_inconsistent_verified_flags() {
    for verified in [None, Some(vec![]), Some(vec![true, false])] {
        let records = PlayerRecords {
            type_: PlayerRecordsType::Add,
            records_count: 1,
            records: vec![add_record()],
            verified,
        };

        let error = encoded_player_records(&records).expect_err("invalid verified flags");
        assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);
    }

    let remove_with_verified = PlayerRecords {
        type_: PlayerRecordsType::Remove,
        records_count: 1,
        records: vec![remove_record()],
        verified: Some(vec![true]),
    };
    let error =
        encoded_player_records(&remove_with_verified).expect_err("remove has no verified flags");
    assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);
}

#[test]
fn player_records_encode_rejects_missing_records_and_unknown_actions() {
    let missing_record = PlayerRecords {
        type_: PlayerRecordsType::Remove,
        records_count: 1,
        records: vec![None],
        verified: None,
    };
    let error = encoded_player_records(&missing_record).expect_err("missing record");
    assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);

    let unknown_action = PlayerRecords {
        type_: PlayerRecordsType::Unknown(2),
        records_count: 0,
        records: vec![],
        verified: None,
    };
    let error = encoded_player_records(&unknown_action).expect_err("unknown action");
    assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);
}
