(component
  (import "$UI" (instance $ui
    (type $value (variant
      (case "boolean" bool)
      (case "integer" s64)
      (case "number" f64)
      (case "text" string)
      (case "numbers" (list f64))))
    (export "value" (type $value-type (eq $value)))
    (export "open-screen" (func (param "template" (option string)) (result (result (error string)))))
    (export "close-screen" (func (result (result (error string)))))
    (export "set-collection" (func (param "name" string) (param "rows-json" (list u8)) (result (result (error string)))))
    (export "set-value" (func (param "name" string) (param "value" $value-type) (result (result (error string)))))))
  (import "$INPUT" (instance $input
    (export "pressed" (func (param "action" string) (result bool)))))
  (alias export $ui "open-screen" (func $open-screen))
  (alias export $ui "close-screen" (func $close-screen))
  (alias export $ui "set-collection" (func $set-collection))
  (alias export $ui "set-value" (func $set-value))
  (alias export $input "pressed" (func $pressed))
  (core module $memory-module
    (memory (export "memory") 1)
    (global $next (mut i32) (i32.const 4096))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $old i32)
      global.get $next local.tee $old
      local.get 3 i32.add global.set $next local.get $old)
    (data (i32.const 0) "$TEMPLATE")
    (data (i32.const 64) "items")
    (data (i32.const 96) "#row"))
  (core instance $mem (instantiate $memory-module))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core func $lower-open (canon lower (func $open-screen) (memory $memory) (realloc $realloc)))
  (core func $lower-close (canon lower (func $close-screen) (memory $memory) (realloc $realloc)))
  (core func $lower-collection (canon lower (func $set-collection) (memory $memory) (realloc $realloc)))
  (core func $lower-value (canon lower (func $set-value) (memory $memory) (realloc $realloc)))
  (core func $lower-pressed (canon lower (func $pressed) (memory $memory)))
  (core module $code
    (import "host" "open" (func $open (param i32 i32 i32 i32)))
    (import "host" "close" (func $close (param i32)))
    (import "host" "collection" (func $collection (param i32 i32 i32 i32 i32)))
    (import "host" "value" (func $value (param i32 i32 i32 i64 i32 i32)))
    (import "host" "pressed" (func $pressed (param i32 i32) (result i32)))
    (import "host" "memory" (memory 1))
    (func (export "init")
      i32.const 1 i32.const 0 i32.const $TEMPLATE_LENGTH i32.const 2048 call $open)
    (func (export "dispatch") (param i32 i32 i32 i32)
      i32.const 64 i32.const 5 local.get 2 local.get 3 i32.const 2048 call $collection)
    (func (export "action") (param i32 i32 i32 i32)
      local.get 0 local.get 1 call $pressed
      if
        i32.const 96 i32.const 4 i32.const 1 local.get 3 i64.extend_i32_u i32.const 0
        i32.const 2048 call $value
      end)
    (func (export "epoch") i32.const 2048 call $close))
  (core instance $host
    (export "open" (func $lower-open))
    (export "close" (func $lower-close))
    (export "collection" (func $lower-collection))
    (export "value" (func $lower-value))
    (export "pressed" (func $lower-pressed))
    (export "memory" (memory $memory)))
  (core instance $run (instantiate $code (with "host" (instance $host))))
  (func (export "init") (canon lift (core func $run "init")))
  (func (export "dispatch") (param "channel" string) (param "record-json" (list u8))
    (canon lift (core func $run "dispatch") (memory $memory) (realloc $realloc)))
  (func (export "action") (param "id" string) (param "collection-index" (option u32))
    (canon lift (core func $run "action") (memory $memory) (realloc $realloc)))
  (func (export "epoch") (canon lift (core func $run "epoch"))))
