[package]
name = "assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
block-transform = { path = "../block-transform" }
bitflags = "2"
flate2 = { version = "1", default-features = false, features = ["zlib-rs"] }
lewton = "0.10.2"
rayon.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2.workspace = true
thiserror.workspace = true
zip = { version = "7", default-features = false, features = ["deflate-flate2-zlib-rs"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1", default-features = false, features = ["fs", "std"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
