[package]
name = "assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
bitflags = "2"
lewton = "0.10.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
