// Code generated by tools/bridgegen/generate.py; DO NOT EDIT.
// Package bridgecontract owns the local Rust/Go transport contract.
package bridgecontract

const (
	// MaxFrameLen: Largest game and session frame payload in bytes.
	MaxFrameLen = 67108864
	// MaxControlFrameLen: Largest control request or response payload in bytes.
	MaxControlFrameLen = 65536
	// MaxPingTargets: Most server addresses admitted in one ping request.
	MaxPingTargets = 64
	// SessionKindConnect: Client session setup carrying JSON login data.
	SessionKindConnect = 1
	// SessionKindBatch: A batch of length-prefixed packets in either direction.
	SessionKindBatch = 2
	// SessionKindHandoff: Core handoff containing JSON and startup packets.
	SessionKindHandoff = 3
	// SessionKindPackData: Core resource-pack index followed by archive bytes.
	SessionKindPackData = 4
	// SessionKindTransfer: Terminal core transfer message.
	SessionKindTransfer = 5
	// SessionKindDisconnect: Terminal core disconnect message.
	SessionKindDisconnect = 6
	// SessionPackChunkBytes: Archive bytes in one resource-pack data frame.
	SessionPackChunkBytes = 4194304
)
