//! Identifiers for existing opt-in UI observations.

pub const USE_ON_IDENTITY_EVIDENCE: &str = "RUST_MCBE_USE_ON_IDENTITY_EVIDENCE";
pub const FORM_SHAPE_PROBE: &str = "RUST_MCBE_FORM_SHAPE_PROBE";
pub const CRAFT_OBSERVATION: &str = "RUST_MCBE_CRAFT_OBSERVATION";
pub const FAST_TRANSFER_ACTION: &str = "RUST_MCBE_FAST_TRANSFER_ACTION";
pub const LOADING_MILESTONE: &str = "RUST_MCBE_LOADING_MILESTONE";
