#!/usr/bin/env python3
"""Generate the Rust and Go local bridge contract from one manifest."""

import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]


def declarations(manifest):
    """Render unique, bounded numeric constants for both bridge implementations."""
    if manifest["schema"] != 1:
        raise ValueError("unsupported bridge contract schema")
    constants = manifest["constants"]
    for key in ("rust_name", "go_name"):
        names = [row[key] for row in constants if row[key]]
        if len(names) != len(set(names)):
            raise ValueError(f"duplicate {key} in bridge contract")
    rust = ["// Generated by tools/bridgegen/generate.py; edit data/contract.json."]
    go = ["// Code generated by tools/bridgegen/generate.py; DO NOT EDIT.",
          "// Package bridgecontract owns the local Rust/Go transport contract.",
          "package bridgecontract", "", "const ("]
    for row in constants:
        value = row["value"]
        limit = 255 if row["rust_type"] == "u8" else 2**32 - 1
        if not isinstance(value, int) or not 0 < value <= limit:
            raise ValueError("bridge contract values must fit their wire types")
        go += [f'    // {row["go_name"]}: {row["doc"]}', f'    {row["go_name"]} = {value}']
        if row["rust_name"]:
            visibility = "pub" if row["rust_name"] == "MAX_FRAME_LEN" else "pub(crate)"
            rust += ["", f'/// {row["doc"]}',
                     f'{visibility} const {row["rust_name"]}: {row["rust_type"]} = {value};']
    go.append(")")
    formatted = subprocess.run(["gofmt"], input="\n".join(go) + "\n", text=True,
                               capture_output=True, check=True).stdout
    return {ROOT / "crates/bridge/src/contract.rs": "\n".join(rust) + "\n",
            ROOT / "core/internal/bridgecontract/contract.go": formatted}


def main():
    """Regenerate constants or reject stale checked-in declarations."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads((ROOT / "crates/bridge/data/contract.json").read_text())
    for path, content in declarations(manifest).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f"stale bridge contract: {path.relative_to(ROOT)}\n")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
