// Generated by tools/registrygen/generate_schema.py; edit registry-schema.json.
use super::Reader;
use crate::AssetError;
use bitflags::bitflags;

pub(super) const REGISTRY_MAGIC: &[u8; 8] = b"BREG1003";
pub(super) const LEGACY_REGISTRY_PROTOCOL: u32 = 1001;
pub(super) const RECORD_HEADER_BYTES: usize = 56;
pub(super) const MAX_REGISTRY_RECORDS: usize = 65536;
pub(super) const MAX_REGISTRY_STATE_BYTES: usize = 1048576;
pub(super) const MAX_COLLISION_BOXES: usize = 7;

bitflags! {
    /// Geometry, occlusion and seasonal shelter facts.
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
    pub struct BlockFlags: u8 {
        const AIR = 1 << 0;
        const CUBE_GEOMETRY = 1 << 1;
        const OCCLUDES_FULL_FACE = 1 << 2;
        const LEAF_MODEL = 1 << 3;
        /// Replaceable-block admission used by the seasonal scan; independent of geometry and collision.
        const SEASONAL_REPLACEABLE = 1 << 4;
        /// Effective catch chance is nonzero.
        const FIRE_FLAMMABLE = 1 << 5;
        /// The support component accepts full support on the top face.
        const FIRE_TOP_SUPPORT = 1 << 6;
    }
}

bitflags! {
    /// Pinned sources that proved the identity of a canonical state.
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
    pub struct RegistryProvenance: u8 {
        const PMMP = 1 << 0;
        const DRAGONFLY = 1 << 1;
        const PRISMARINE = 1 << 2;
        const VALENTINE = 1 << 3;
    }
}

/// A byte-sized registry discriminator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum ModelFamily {
    #[default]
    Unknown = 0,
    Air = 1,
    Cube = 2,
    Leaves = 3,
    Cross = 4,
    Crop = 5,
    Liquid = 6,
    Slab = 7,
    Stair = 8,
    Door = 9,
    Trapdoor = 10,
    Pane = 11,
    Fence = 12,
    Gate = 13,
    Chest = 14,
    Sign = 15,
    Wall = 16,
    Bed = 17,
    Rail = 18,
    Torch = 19,
    Button = 20,
    PressurePlate = 21,
    Carpet = 22,
    Layer = 23,
    Decorative = 24,
    Statue = 25,
    Cuboid = 26,
    Aquatic = 27,
    Cocoa = 28,
    Lever = 29,
    Invisible = 30,
    FlowerBed = 31,
    Vine = 32,
    GlowLichen = 33,
    SculkVein = 34,
    ChiseledBookshelf = 35,
    ResinClump = 36,
}

impl ModelFamily {
    /// Decode a known discriminator and reject reserved values.
    pub(super) fn read(raw: u8) -> Result<Self, AssetError> {
        match raw {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::Air),
            2 => Ok(Self::Cube),
            3 => Ok(Self::Leaves),
            4 => Ok(Self::Cross),
            5 => Ok(Self::Crop),
            6 => Ok(Self::Liquid),
            7 => Ok(Self::Slab),
            8 => Ok(Self::Stair),
            9 => Ok(Self::Door),
            10 => Ok(Self::Trapdoor),
            11 => Ok(Self::Pane),
            12 => Ok(Self::Fence),
            13 => Ok(Self::Gate),
            14 => Ok(Self::Chest),
            15 => Ok(Self::Sign),
            16 => Ok(Self::Wall),
            17 => Ok(Self::Bed),
            18 => Ok(Self::Rail),
            19 => Ok(Self::Torch),
            20 => Ok(Self::Button),
            21 => Ok(Self::PressurePlate),
            22 => Ok(Self::Carpet),
            23 => Ok(Self::Layer),
            24 => Ok(Self::Decorative),
            25 => Ok(Self::Statue),
            26 => Ok(Self::Cuboid),
            27 => Ok(Self::Aquatic),
            28 => Ok(Self::Cocoa),
            29 => Ok(Self::Lever),
            30 => Ok(Self::Invisible),
            31 => Ok(Self::FlowerBed),
            32 => Ok(Self::Vine),
            33 => Ok(Self::GlowLichen),
            34 => Ok(Self::SculkVein),
            35 => Ok(Self::ChiseledBookshelf),
            36 => Ok(Self::ResinClump),
            _ => Err(AssetError::InvalidRegistryFlags(raw)),
        }
    }
}

/// A byte-sized registry discriminator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum ContributorRole {
    #[default]
    Primary = 0,
    LiquidAdditional = 1,
    Air = 2,
}

impl ContributorRole {
    /// Decode a known discriminator and reject reserved values.
    pub(crate) fn read(raw: u8) -> Result<Self, AssetError> {
        match raw {
            0 => Ok(Self::Primary),
            1 => Ok(Self::LiquidAdditional),
            2 => Ok(Self::Air),
            _ => Err(AssetError::InvalidRegistryFlags(raw)),
        }
    }
}

/// A byte-sized registry discriminator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ModelStateField {
    Orientation = 1,
    Half = 2,
    Open = 3,
    Hinge = 4,
    Connections = 5,
    Growth = 6,
    LiquidDepth = 7,
    Flags = 8,
}

/// A byte-sized registry discriminator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum CollisionConfidence {
    #[default]
    None = 0,
    CollisionOnly = 1,
    ReviewedVisibleBounds = 2,
}

impl CollisionConfidence {
    /// Decode a known discriminator and reject reserved values.
    pub(super) fn read(raw: u8) -> Result<Self, AssetError> {
        match raw {
            0 => Ok(Self::None),
            1 => Ok(Self::CollisionOnly),
            2 => Ok(Self::ReviewedVisibleBounds),
            _ => Err(AssetError::InvalidRegistryFlags(raw)),
        }
    }
}

/// Presence-tagged model-state fields.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct ModelState {
    pub(super) mask: u8,
    pub(super) values: [u32; 8],
}

/// Signed 1/100,000,000-block coordinates from the pinned collision-shape source.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct CollisionBox {
    pub min_x: i32,
    pub min_y: i32,
    pub min_z: i32,
    pub max_x: i32,
    pub max_y: i32,
    pub max_z: i32,
}

/// A carrier-local collision shape; compare boxes when checking geometry.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CollisionSeed {
    pub shape_id: u16,
    pub confidence: CollisionConfidence,
    pub boxes: Box<[CollisionBox]>,
}

/// One canonical state from the deterministic block registry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegistryRecord {
    pub sequential_id: u32,
    pub network_hash: u32,
    pub name: Box<str>,
    pub canonical_state: Box<str>,
    pub flags: BlockFlags,
    pub model_family: ModelFamily,
    pub contributor_role: ContributorRole,
    pub model_state: ModelState,
    pub face_coverage: u8,
    pub collision_seed: CollisionSeed,
    pub provenance: RegistryProvenance,
}

/// Counts and protocol in the block-registry header.
#[derive(Debug, Clone, Copy)]
pub struct RegistryMetadata {
    pub protocol: u32,
    pub canonical_names: u32,
    pub canonical_states: u32,
    pub valentine_names: u32,
    pub valentine_states: u32,
    pub valentine_gap_names: u32,
    pub valentine_gap_states: u32,
}

/// Read RegistryMetadata fields in their declared little-endian order.
pub(super) fn read_registry_metadata(
    reader: &mut Reader<'_>,
) -> Result<RegistryMetadata, AssetError> {
    Ok(RegistryMetadata {
        protocol: reader.read_u32("protocol")?,
        canonical_names: reader.read_u32("canonical_names")?,
        canonical_states: reader.read_u32("canonical_states")?,
        valentine_names: reader.read_u32("valentine_names")?,
        valentine_states: reader.read_u32("valentine_states")?,
        valentine_gap_names: reader.read_u32("valentine_gap_names")?,
        valentine_gap_states: reader.read_u32("valentine_gap_states")?,
    })
}

/// Read CollisionBox fields in their declared little-endian order.
pub(super) fn read_collision_box(reader: &mut Reader<'_>) -> Result<CollisionBox, AssetError> {
    Ok(CollisionBox {
        min_x: reader.read_i32("min_x")?,
        min_y: reader.read_i32("min_y")?,
        min_z: reader.read_i32("min_z")?,
        max_x: reader.read_i32("max_x")?,
        max_y: reader.read_i32("max_y")?,
        max_z: reader.read_i32("max_z")?,
    })
}

/// The fixed-size portion of one little-endian record.
pub(super) struct RecordHeader {
    pub(super) sequential_id: u32,
    pub(super) network_hash: u32,
    pub(super) raw_flags: u8,
    pub(super) model_family: u8,
    pub(super) contributor_role: u8,
    pub(super) model_mask: u8,
    pub(super) face_coverage: u8,
    pub(super) confidence: u8,
    pub(super) raw_provenance: u8,
    pub(super) box_count: u8,
    pub(super) shape_id: u16,
    pub(super) name_len: u16,
    pub(super) state_len: u32,
    pub(super) values: [u32; 8],
}

/// Read the fixed header in schema order before validating its facts.
pub(super) fn read_record_header(reader: &mut Reader<'_>) -> Result<RecordHeader, AssetError> {
    Ok(RecordHeader {
        sequential_id: reader.read_u32("record sequential_id")?,
        network_hash: reader.read_u32("record network_hash")?,
        raw_flags: reader.read_u8("record raw_flags")?,
        model_family: reader.read_u8("record model_family")?,
        contributor_role: reader.read_u8("record contributor_role")?,
        model_mask: reader.read_u8("record model_mask")?,
        face_coverage: reader.read_u8("record face_coverage")?,
        confidence: reader.read_u8("record confidence")?,
        raw_provenance: reader.read_u8("record raw_provenance")?,
        box_count: reader.read_u8("record box_count")?,
        shape_id: reader.read_u16("record shape_id")?,
        name_len: reader.read_u16("record name_len")?,
        state_len: reader.read_u32("record state_len")?,
        values: {
            let mut values = [0; 8];
            for value in &mut values {
                *value = reader.read_u32("record values")?;
            }
            values
        },
    })
}
