#!/usr/bin/env python3
"""Generate the Go and Rust block-registry contract from its shared schema."""

import argparse
import json
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "crates/assets/data/registry-schema.json"


def validate(schema):
    """Reject ambiguous discriminants, flag bits and unsupported wire fields."""
    if len(schema["magic"].encode("ascii")) != 8:
        raise ValueError("registry magic must contain eight ASCII bytes")
    for enum in schema["enums"]:
        values = enum["values"]
        numbers = [v["value"] for v in values]
        names = [v["name"] for v in values]
        if len(set(numbers)) != len(numbers) or len(set(names)) != len(names):
            raise ValueError(f"duplicate enum member in {enum['name']}")
        if any(not 0 <= v <= 255 for v in numbers):
            raise ValueError("registry enums must fit in a byte")
        if numbers != list(range(numbers[0], numbers[-1] + 1)):
            raise ValueError("registry enums need ascending contiguous discriminants")
        if enum["default"] and enum["default"] not in names:
            raise ValueError("enum default must name a member")
    for flags in schema["flags"]:
        bits = [v["bit"] for v in flags["values"]]
        if len(set(bits)) != len(bits) or any(not 0 <= v < 8 for v in bits):
            raise ValueError("registry flags need unique byte-sized bits")
    fields = schema["record_header"]
    if len({v["name"] for v in fields}) != len(fields):
        raise ValueError("duplicate record header field")
    if any(v["type"] not in {"u8", "u16", "u32", "u32[8]"} for v in fields):
        raise ValueError("unsupported record header field")


def rust_declarations(schema):
    """Render the reader's public types and bounded wire-header decoder."""
    lines = [
        "// Generated by tools/registrygen/generate_schema.py; edit registry-schema.json.",
        "use bitflags::bitflags;",
        "use super::Reader;",
        "use crate::AssetError;",
        "",
        f'pub(super) const REGISTRY_MAGIC: &[u8; 8] = b"{schema["magic"]}";',
        f'pub(super) const LEGACY_REGISTRY_PROTOCOL: u32 = {schema["legacy_protocol"]};',
    ]
    size = sum({"u8": 1, "u16": 2, "u32": 4, "u32[8]": 32}[f["type"]]
               for f in schema["record_header"])
    lines.append(f"pub(super) const RECORD_HEADER_BYTES: usize = {size};")
    for limit in schema["limits"]:
        if limit["rust_name"]:
            lines.append(f'pub(super) const {limit["rust_name"]}: usize = {limit["value"]};')
    for flags in schema["flags"]:
        lines += ["", "bitflags! {", f'    /// {flags["doc"]}',
                  "    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]",
                  f'    pub struct {flags["name"]}: u8 {{']
        for value in flags["values"]:
            if value.get("doc"):
                lines.append(f'        /// {value["doc"]}')
            lines.append(f'        const {value["name"]} = 1 << {value["bit"]};')
        lines += ["    }", "}"]
    for enum in schema["enums"]:
        derive = "Debug, Clone, Copy, PartialEq, Eq, Hash"
        if enum["default"]:
            derive += ", Default"
        name = enum["name"]
        lines += ["", "/// A byte-sized registry discriminator.",
                  f"#[derive({derive})]", "#[repr(u8)]", f"pub enum {name} {{"]
        for value in enum["values"]:
            if value["name"] == enum["default"]:
                lines.append("    #[default]")
            lines.append(f'    {value["name"]} = {value["value"]},')
        lines.append("}")
        if enum["read"]:
            lines += ["", f"impl {name} {{",
                      "    /// Decode a known discriminator and reject reserved values.",
                      f'    {enum["read_visibility"]} fn read(raw: u8) -> Result<Self, AssetError> {{',
                      "        match raw {"]
            for value in enum["values"]:
                lines.append(f'            {value["value"]} => Ok(Self::{value["name"]}),')
            lines += ["            _ => Err(AssetError::InvalidRegistryFlags(raw)),",
                      "        }", "    }", "}"]
    for struct in schema["structs"]:
        lines += ["", f'/// {struct["doc"]}',
                  f'#[derive({struct["derive"]})]', f'pub struct {struct["rust_name"]} {{']
        for field in struct["fields"]:
            visibility = "pub" if field["public"] else "pub(super)"
            lines.append(f'    {visibility} {field["rust_name"]}: {field["rust_type"]},')
        lines.append("}")
    for name in ("RegistryMetadata", "CollisionBox"):
        struct = next(s for s in schema["structs"] if s["rust_name"] == name)
        function = "read_registry_metadata" if name == "RegistryMetadata" else "read_collision_box"
        lines += ["", f"/// Read {name} fields in their declared little-endian order.",
                  f"pub(super) fn {function}(reader: &mut Reader<'_>) -> Result<{name}, AssetError> {{",
                  f"    Ok({name} {{"]
        for field in struct["fields"]:
            kind, field_name = field["rust_type"], field["rust_name"]
            lines.append(f'        {field_name}: reader.read_{kind}("{field_name}")?,')
        lines += ["    })", "}"]
    lines += ["", "/// The fixed-size portion of one little-endian record.",
              "pub(super) struct RecordHeader {"]
    for field in schema["record_header"]:
        kind = "[u32; 8]" if field["type"] == "u32[8]" else field["type"]
        lines.append(f'    pub(super) {field["name"]}: {kind},')
    lines += ["}", "", "/// Read the fixed header in schema order before validating its facts.",
              "pub(super) fn read_record_header(reader: &mut Reader<'_>) -> Result<RecordHeader, AssetError> {",
              "    Ok(RecordHeader {"]
    for field in schema["record_header"]:
        name, kind = field["name"], field["type"]
        if kind == "u32[8]":
            lines += [f"        {name}: {{", "            let mut values = [0; 8];",
                      "            for value in &mut values {",
                      f'                *value = reader.read_u32("record {name}")?;',
                      "            }", "            values", "        },"]
        else:
            lines.append(f'        {name}: reader.read_{kind}("record {name}")?,')
    lines += ["    })", "}"]
    return "\n".join(lines) + "\n"


def go_declarations(schema):
    """Render generator declarations and the matching record-header encoder."""
    lines = ["// Code generated by generate_schema.py; DO NOT EDIT.", "package main", "",
             'import "encoding/binary"', "", "const (",
             f'    registryHeader = "{schema["magic"]}"',
             f'    registryProtocol = {schema["legacy_protocol"]}']
    for limit in schema["limits"]:
        lines.append(f'    {limit["go_name"]} = {limit["value"]}')
    lines.append(f'    registryHeaderBytes = {len(schema["magic"]) + 4 * len(next(s for s in schema["structs"] if s["go_name"] == "RegistryMetadata")["fields"])}')
    lines.append(f'    recordHeaderBytes = {sum({"u8": 1, "u16": 2, "u32": 4, "u32[8]": 32}[f["type"]] for f in schema["record_header"])}')
    lines.append(f'    collisionBoxBytes = {4 * len(next(s for s in schema["structs"] if s["go_name"] == "CollisionBox")["fields"])}')
    lines.append(")")
    for flags in schema["flags"]:
        lines += ["", "const ("]
        source = [v for v in flags["values"] if v["source"]]
        for value in source:
            lines.append(f'    {value["go_name"]} uint8 = 1 << {value["bit"]}')
        lines.append(f'    {flags["go_all"]} = ' + " | ".join(v["go_name"] for v in source))
        lines.append(")")
    for enum in schema["enums"]:
        name = enum["name"]
        lines += ["", f"// {name} is a byte-sized registry discriminator.",
                  f"type {name} uint8", "", "const ("]
        for value in enum["values"]:
            lines.append(f'    {enum["go_prefix"]}{value["name"]} {name} = {value["value"]}')
        lines += [")", f'const {enum["go_max"]} = {enum["go_prefix"]}{enum["values"][-1]["name"]}']
    for struct in schema["structs"]:
        name = struct["go_name"]
        lines += ["", f"// {name} is a typed block-registry value.", f"type {name} struct {{"]
        for field in struct["fields"]:
            lines.append(f'    {field["go_name"]} {field["go_type"]}')
        lines.append("}")
    for name in ("RegistryMetadata", "CollisionBox"):
        struct = next(s for s in schema["structs"] if s["go_name"] == name)
        function = "appendRegistryMetadata" if name == "RegistryMetadata" else "appendCollisionBox"
        lines += ["", f"// {function} writes {name} in its declared little-endian order.",
                  f"func {function}(encoded []byte, value {name}) []byte {{"]
        if name == "RegistryMetadata":
            lines.append("    encoded = append(encoded, registryHeader...)")
        for field in struct["fields"]:
            lines.append(f'    encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.{field["go_name"]}))')
        lines += ["    return encoded", "}"]
        function = "decode" + name
        lines += ["", f"// {function} reads fields from a previously length-checked slice.",
                  f"func {function}(data []byte) {name} {{", f"    return {name} {{"]
        for index, field in enumerate(struct["fields"]):
            lines.append(f'        {field["go_name"]}: {field["go_type"]}(binary.LittleEndian.Uint32(data[{index * 4}:{index * 4 + 4}])),')
        lines += ["    }", "}"]
    lines += ["", "// RecordHeader is the fixed-size portion of a little-endian record.",
              "type RecordHeader struct {"]
    for field in schema["record_header"]:
        kind = "[8]uint32" if field["type"] == "u32[8]" else "uint" + field["type"][1:]
        lines.append(f'    {go_field_name(field["name"])} {kind}')
    lines += ["}", "", "// decodeRecordHeader reads a previously length-checked record prefix.",
              "func decodeRecordHeader(data []byte) RecordHeader {", "    var value RecordHeader"]
    offset = 0
    for field in schema["record_header"]:
        name, kind = go_field_name(field["name"]), field["type"]
        if kind == "u32[8]":
            lines += [f"    for index := range value.{name} {{",
                      f"        value.{name}[index] = binary.LittleEndian.Uint32(data[{offset}+index*4:{offset+4}+index*4])", "    }"]
            offset += 32
        elif kind == "u8":
            lines.append(f"    value.{name} = data[{offset}]")
            offset += 1
        else:
            size = {"u16": 2, "u32": 4}[kind]
            lines.append(f"    value.{name} = binary.LittleEndian.Uint{kind[1:]}(data[{offset}:{offset+size}])")
            offset += size
    lines += ["    return value", "}"]
    lines += ["", "// appendRecordHeader writes the already-validated fixed record header.",
              "func appendRecordHeader(encoded []byte, record Record) []byte {"]
    for field in schema["record_header"]:
        kind, value = field["type"], field["go_value"]
        if kind == "u8":
            lines.append(f"    encoded = append(encoded, {value})")
        elif kind == "u32[8]":
            lines += [f"    for _, value := range {value} {{",
                      "        encoded = binary.LittleEndian.AppendUint32(encoded, value)", "    }"]
        else:
            lines.append(f"    encoded = binary.LittleEndian.AppendUint{kind[1:]}(encoded, {value})")
    lines += ["    return encoded", "}"]
    return "\n".join(lines) + "\n"


def go_field_name(name):
    """Convert the schema's snake-case wire names to exported Go members."""
    return "".join(part.upper() if part == "id" else part.capitalize() for part in name.split("_"))


def outputs(schema):
    """Format both declarations with the standard language formatters."""
    validate(schema)
    rust = subprocess.run(["rustfmt", "--edition", "2024", "--emit", "stdout"],
                          input=rust_declarations(schema), text=True, capture_output=True, check=True).stdout
    go = subprocess.run(["gofmt"], input=go_declarations(schema), text=True,
                        capture_output=True, check=True).stdout
    return {ROOT / "crates/assets/src/registry/schema.rs": rust,
            ROOT / "tools/registrygen/schema_generated.go": go}


def main():
    """Regenerate declarations, or fail if the checked-in contract is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs(json.loads(SCHEMA.read_text())).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f"stale registry declaration: {path.relative_to(ROOT)}\n")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
