// Code generated by generate_schema.py; DO NOT EDIT.
package main

import "encoding/binary"

const (
	registryHeader             = "BREG1003"
	registryProtocol           = 1001
	maxRecordCount             = 65536
	maxStateBytes              = 1048576
	maxCollisionBoxesPerRecord = 7
	maxNameBytes               = 65535
	registryHeaderBytes        = 36
	recordHeaderBytes          = 56
	collisionBoxBytes          = 24
)

const (
	flagAir              uint8 = 1 << 0
	flagCubeGeometry     uint8 = 1 << 1
	flagOccludesFullFace uint8 = 1 << 2
	flagLeafModel        uint8 = 1 << 3
	allBlockFlags              = flagAir | flagCubeGeometry | flagOccludesFullFace | flagLeafModel
)

const (
	ProvenancePMMP       uint8 = 1 << 0
	ProvenanceDragonfly  uint8 = 1 << 1
	ProvenancePrismarine uint8 = 1 << 2
	ProvenanceValentine  uint8 = 1 << 3
	allProvenance              = ProvenancePMMP | ProvenanceDragonfly | ProvenancePrismarine | ProvenanceValentine
)

// ModelFamily is a byte-sized registry discriminator.
type ModelFamily uint8

const (
	ModelFamilyUnknown           ModelFamily = 0
	ModelFamilyAir               ModelFamily = 1
	ModelFamilyCube              ModelFamily = 2
	ModelFamilyLeaves            ModelFamily = 3
	ModelFamilyCross             ModelFamily = 4
	ModelFamilyCrop              ModelFamily = 5
	ModelFamilyLiquid            ModelFamily = 6
	ModelFamilySlab              ModelFamily = 7
	ModelFamilyStair             ModelFamily = 8
	ModelFamilyDoor              ModelFamily = 9
	ModelFamilyTrapdoor          ModelFamily = 10
	ModelFamilyPane              ModelFamily = 11
	ModelFamilyFence             ModelFamily = 12
	ModelFamilyGate              ModelFamily = 13
	ModelFamilyChest             ModelFamily = 14
	ModelFamilySign              ModelFamily = 15
	ModelFamilyWall              ModelFamily = 16
	ModelFamilyBed               ModelFamily = 17
	ModelFamilyRail              ModelFamily = 18
	ModelFamilyTorch             ModelFamily = 19
	ModelFamilyButton            ModelFamily = 20
	ModelFamilyPressurePlate     ModelFamily = 21
	ModelFamilyCarpet            ModelFamily = 22
	ModelFamilyLayer             ModelFamily = 23
	ModelFamilyDecorative        ModelFamily = 24
	ModelFamilyStatue            ModelFamily = 25
	ModelFamilyCuboid            ModelFamily = 26
	ModelFamilyAquatic           ModelFamily = 27
	ModelFamilyCocoa             ModelFamily = 28
	ModelFamilyLever             ModelFamily = 29
	ModelFamilyInvisible         ModelFamily = 30
	ModelFamilyFlowerBed         ModelFamily = 31
	ModelFamilyVine              ModelFamily = 32
	ModelFamilyGlowLichen        ModelFamily = 33
	ModelFamilySculkVein         ModelFamily = 34
	ModelFamilyChiseledBookshelf ModelFamily = 35
	ModelFamilyResinClump        ModelFamily = 36
)
const maxModelFamily = ModelFamilyResinClump

// ContributorRole is a byte-sized registry discriminator.
type ContributorRole uint8

const (
	ContributorPrimary          ContributorRole = 0
	ContributorLiquidAdditional ContributorRole = 1
	ContributorAir              ContributorRole = 2
)
const maxContributorRole = ContributorAir

// ModelStateField is a byte-sized registry discriminator.
type ModelStateField uint8

const (
	ModelStateOrientation ModelStateField = 1
	ModelStateHalf        ModelStateField = 2
	ModelStateOpen        ModelStateField = 3
	ModelStateHinge       ModelStateField = 4
	ModelStateConnections ModelStateField = 5
	ModelStateGrowth      ModelStateField = 6
	ModelStateLiquidDepth ModelStateField = 7
	ModelStateFlags       ModelStateField = 8
)
const maxModelStateField = ModelStateFlags

// CollisionConfidence is a byte-sized registry discriminator.
type CollisionConfidence uint8

const (
	CollisionConfidenceNone                  CollisionConfidence = 0
	CollisionConfidenceCollisionOnly         CollisionConfidence = 1
	CollisionConfidenceReviewedVisibleBounds CollisionConfidence = 2
)
const maxCollisionConfidence = CollisionConfidenceReviewedVisibleBounds

// ModelState is a typed block-registry value.
type ModelState struct {
	Mask   uint8
	Values [8]uint32
}

// CollisionBox is a typed block-registry value.
type CollisionBox struct {
	MinX int32
	MinY int32
	MinZ int32
	MaxX int32
	MaxY int32
	MaxZ int32
}

// CollisionSeed is a typed block-registry value.
type CollisionSeed struct {
	ShapeID    uint16
	Confidence CollisionConfidence
	Boxes      []CollisionBox
}

// Record is a typed block-registry value.
type Record struct {
	SequentialID    uint32
	NetworkHash     uint32
	Name            string
	StateJSON       []byte
	Flags           uint8
	ModelFamily     ModelFamily
	ContributorRole ContributorRole
	ModelState      ModelState
	FaceCoverage    uint8
	CollisionSeed   CollisionSeed
	Provenance      uint8
}

// RegistryMetadata is a typed block-registry value.
type RegistryMetadata struct {
	Protocol           uint32
	CanonicalNames     uint32
	CanonicalStates    uint32
	ValentineNames     uint32
	ValentineStates    uint32
	ValentineGapNames  uint32
	ValentineGapStates uint32
}

// appendRegistryMetadata writes RegistryMetadata in its declared little-endian order.
func appendRegistryMetadata(encoded []byte, value RegistryMetadata) []byte {
	encoded = append(encoded, registryHeader...)
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.Protocol))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.CanonicalNames))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.CanonicalStates))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.ValentineNames))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.ValentineStates))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.ValentineGapNames))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.ValentineGapStates))
	return encoded
}

// decodeRegistryMetadata reads fields from a previously length-checked slice.
func decodeRegistryMetadata(data []byte) RegistryMetadata {
	return RegistryMetadata{
		Protocol:           uint32(binary.LittleEndian.Uint32(data[0:4])),
		CanonicalNames:     uint32(binary.LittleEndian.Uint32(data[4:8])),
		CanonicalStates:    uint32(binary.LittleEndian.Uint32(data[8:12])),
		ValentineNames:     uint32(binary.LittleEndian.Uint32(data[12:16])),
		ValentineStates:    uint32(binary.LittleEndian.Uint32(data[16:20])),
		ValentineGapNames:  uint32(binary.LittleEndian.Uint32(data[20:24])),
		ValentineGapStates: uint32(binary.LittleEndian.Uint32(data[24:28])),
	}
}

// appendCollisionBox writes CollisionBox in its declared little-endian order.
func appendCollisionBox(encoded []byte, value CollisionBox) []byte {
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.MinX))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.MinY))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.MinZ))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.MaxX))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.MaxY))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(value.MaxZ))
	return encoded
}

// decodeCollisionBox reads fields from a previously length-checked slice.
func decodeCollisionBox(data []byte) CollisionBox {
	return CollisionBox{
		MinX: int32(binary.LittleEndian.Uint32(data[0:4])),
		MinY: int32(binary.LittleEndian.Uint32(data[4:8])),
		MinZ: int32(binary.LittleEndian.Uint32(data[8:12])),
		MaxX: int32(binary.LittleEndian.Uint32(data[12:16])),
		MaxY: int32(binary.LittleEndian.Uint32(data[16:20])),
		MaxZ: int32(binary.LittleEndian.Uint32(data[20:24])),
	}
}

// RecordHeader is the fixed-size portion of a little-endian record.
type RecordHeader struct {
	SequentialID    uint32
	NetworkHash     uint32
	RawFlags        uint8
	ModelFamily     uint8
	ContributorRole uint8
	ModelMask       uint8
	FaceCoverage    uint8
	Confidence      uint8
	RawProvenance   uint8
	BoxCount        uint8
	ShapeID         uint16
	NameLen         uint16
	StateLen        uint32
	Values          [8]uint32
}

// decodeRecordHeader reads a previously length-checked record prefix.
func decodeRecordHeader(data []byte) RecordHeader {
	var value RecordHeader
	value.SequentialID = binary.LittleEndian.Uint32(data[0:4])
	value.NetworkHash = binary.LittleEndian.Uint32(data[4:8])
	value.RawFlags = data[8]
	value.ModelFamily = data[9]
	value.ContributorRole = data[10]
	value.ModelMask = data[11]
	value.FaceCoverage = data[12]
	value.Confidence = data[13]
	value.RawProvenance = data[14]
	value.BoxCount = data[15]
	value.ShapeID = binary.LittleEndian.Uint16(data[16:18])
	value.NameLen = binary.LittleEndian.Uint16(data[18:20])
	value.StateLen = binary.LittleEndian.Uint32(data[20:24])
	for index := range value.Values {
		value.Values[index] = binary.LittleEndian.Uint32(data[24+index*4 : 28+index*4])
	}
	return value
}

// appendRecordHeader writes the already-validated fixed record header.
func appendRecordHeader(encoded []byte, record Record) []byte {
	encoded = binary.LittleEndian.AppendUint32(encoded, record.SequentialID)
	encoded = binary.LittleEndian.AppendUint32(encoded, record.NetworkHash)
	encoded = append(encoded, record.Flags)
	encoded = append(encoded, uint8(record.ModelFamily))
	encoded = append(encoded, uint8(record.ContributorRole))
	encoded = append(encoded, record.ModelState.Mask)
	encoded = append(encoded, record.FaceCoverage)
	encoded = append(encoded, uint8(record.CollisionSeed.Confidence))
	encoded = append(encoded, record.Provenance)
	encoded = append(encoded, uint8(len(record.CollisionSeed.Boxes)))
	encoded = binary.LittleEndian.AppendUint16(encoded, record.CollisionSeed.ShapeID)
	encoded = binary.LittleEndian.AppendUint16(encoded, uint16(len(record.Name)))
	encoded = binary.LittleEndian.AppendUint32(encoded, uint32(len(record.StateJSON)))
	for _, value := range record.ModelState.Values {
		encoded = binary.LittleEndian.AppendUint32(encoded, value)
	}
	return encoded
}
