"""Refresh derived carrier hashes after running registrygen."""

import argparse
import hashlib
import json
from pathlib import Path


def digest(path):
    """Hash a generated artifact without changing its contents."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path, value):
    """Write a stable manifest beneath the selected output directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n")


def refresh(root, output):
    """Derive target, foundation and fallback bindings from generated bytes."""
    target_path = Path("assets/bedrock-target.json")
    target = json.loads((root / target_path).read_text())
    for name in target["hashes"]:
        target["hashes"][name] = digest(root / target["artifacts"][name])
    write_json(output / target_path, target)
    protocol = target["wire_protocol"]
    foundation_path = Path(f"assets/registry-foundation-v{protocol}.json")
    foundation = json.loads((root / foundation_path).read_text())
    for name, binding in foundation["projection_bindings"].items():
        binding["sha256"] = digest(root / foundation["outputs"][name])
    write_json(output / foundation_path, foundation)
    fallback_path = Path(f"assets/vanilla-fallback-source-v{protocol}.json")
    fallback = json.loads((root / fallback_path).read_text())
    for name in ("inventory", "input_inventory", "registry", "legacy_registry"):
        fallback[name]["sha256"] = digest(root / fallback[name]["path"])
    write_json(output / fallback_path, fallback)


def main():
    """Refresh bindings in place or reproduce them in a scratch directory."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    refresh(args.root, args.out)


if __name__ == "__main__":
    main()
