package main

import (
	"io"
	"testing"

	"github.com/df-mc/dragonfly/server/session"
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol/packet"
)

type cameraFixtureConn struct {
	session.Conn
	read, written []packet.Packet
}

// ReadPacket feeds a bounded command sequence into the fixture interceptor.
func (c *cameraFixtureConn) ReadPacket() (packet.Packet, error) {
	if len(c.read) == 0 {
		return nil, io.EOF
	}
	p := c.read[0]
	c.read = c.read[1:]
	return p, nil
}

// WritePacket records the server traffic generated by a fixture command.
func (c *cameraFixtureConn) WritePacket(p packet.Packet) error {
	c.written = append(c.written, p)
	return nil
}

func TestCameraFixtureUsesLatestPlayerPositionAndPreservesOtherCommands(t *testing.T) {
	origin := mgl32.Vec3{40, 65, -10}
	movement := &packet.PlayerAuthInput{Position: origin}
	ordinary := &packet.CommandRequest{CommandLine: "/cameratest unknown"}
	inner := &cameraFixtureConn{read: []packet.Packet{movement, &packet.CommandRequest{CommandLine: "/cameratest aim"}, ordinary}}
	conn := &cameraTestConn{Conn: inner}
	if got, err := conn.ReadPacket(); err != nil || got != movement {
		t.Fatalf("movement was intercepted: %v, %v", got, err)
	}
	if got, err := conn.ReadPacket(); err != nil || got != ordinary {
		t.Fatalf("ordinary command was intercepted: %v, %v", got, err)
	}
	if len(inner.written) != 4 {
		t.Fatalf("aim packet count: %d", len(inner.written))
	}
	actor := inner.written[2].(*packet.AddActor)
	if actor.Position != origin.Add(mgl32.Vec3{1, -1.6, 5}) {
		t.Fatalf("actor was not placed relative to player: %v", actor.Position)
	}
	if _, ok := inner.written[3].(*packet.CameraAimAssist); !ok {
		t.Fatal("aim settings must follow their registry and target")
	}
}

func TestCameraFixtureClearRemovesBothOverridesAndTarget(t *testing.T) {
	packets := cameraFixturePackets("clear", mgl32.Vec3{})
	clear, ok := packets[0].(*packet.CameraInstruction).Clear.Value()
	if !ok || !clear || packets[1].(*packet.CameraAimAssist).Action != packet.CameraAimAssistActionClear {
		t.Fatal("clear did not reset both camera systems")
	}
	if packets[2].(*packet.RemoveActor).EntityUniqueID != cameraFixtureActor {
		t.Fatal("clear did not remove its synthetic target")
	}
}
