(component
  (import "$RENDER" (instance $render
    (type $v (record (field "x" f32) (field "y" f32) (field "z" f32)))
    (export "vector3" (type $vector3 (eq $v)))
    (type $c (record (field "r" f32) (field "g" f32) (field "b" f32) (field "a" f32)))
    (export "rgba" (type $rgba (eq $c)))
    (type $ds (enum "telegraph" "disc" "crater" "shockwave" "dust"))
    (export "decal-style" (type $decal-style (eq $ds)))
    (type $d (record (field "center" $vector3) (field "radius" f32) (field "color" $rgba)
      (field "progress" f32) (field "style" $decal-style)))
    (export "decal" (type $decal (eq $d)))
    (type $r (record (field "points" (list $vector3)) (field "width" f32) (field "color" $rgba)))
    (export "ribbon" (type $ribbon (eq $r)))
    (type $b (record (field "start" $vector3) (field "end" $vector3) (field "width" f32)
      (field "color" $rgba) (field "intensity" f32)))
    (export "beam" (type $beam (eq $b)))
    (type $bp (enum "solid" "soft-disc" "ring" "spark" "silhouette" "sphere" "aura"))
    (export "billboard-pattern" (type $billboard-pattern (eq $bp)))
    (type $bb (record (field "position" $vector3) (field "width" f32) (field "height" f32)
      (field "color" $rgba) (field "pattern" $billboard-pattern) (field "upright" bool)))
    (export "billboard" (type $billboard (eq $bb)))
    (type $pr (record (field "decals" (list $decal)) (field "ribbons" (list $ribbon))
      (field "beams" (list $beam)) (field "billboards" (list $billboard))))
    (export "primitives" (type $primitives (eq $pr)))
    (type $ps (record (field "name" string) (field "order" s32) (field "source" string)
      (field "depth" bool)))
    (export "pass-spec" (type $pass-spec (eq $ps)))
    (export "register-pass" (func (param "spec" $pass-spec) (result (result (error string)))))
    (export "remove-pass" (func (param "name" string) (result (result (error string)))))
    (export "update-pass" (func (param "name" string) (param "enabled" bool)
      (param "params" (list f32)) (result (result (error string)))))
    (export "draw" (func (param "primitives" $primitives) (result (result (error string)))))))
  (alias export $render "register-pass" (func $register))
  (alias export $render "remove-pass" (func $remove))
  (alias export $render "update-pass" (func $update))
  (alias export $render "draw" (func $draw))
  (core module $memory-module
    (memory (export "memory") 1)
    (global $next (mut i32) (i32.const 32768))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $old i32)
      global.get $next local.tee $old
      local.get 3 i32.add global.set $next local.get $old))
  (core instance $mem (instantiate $memory-module))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core func $lower-register (canon lower (func $register) (memory $memory) (realloc $realloc)))
  (core func $lower-remove (canon lower (func $remove) (memory $memory) (realloc $realloc)))
  (core func $lower-update (canon lower (func $update) (memory $memory) (realloc $realloc)))
  (core func $lower-draw (canon lower (func $draw) (memory $memory) (realloc $realloc)))
  (core module $code
    (import "host" "register" (func $register (param i32 i32 i32 i32 i32 i32 i32)))
    (import "host" "remove" (func $remove (param i32 i32 i32)))
    (import "host" "update" (func $update (param i32 i32 i32 i32 i32 i32)))
    (import "host" "draw" (func $draw (param i32 i32 i32 i32 i32 i32 i32 i32 i32)))
    (import "host" "memory" (memory 1))
    (data (i32.const 1024) "$DATA")
    (func (export "init") $INIT)
    (func (export "frame") $FRAME))
  (core instance $host
    (export "register" (func $lower-register))
    (export "remove" (func $lower-remove))
    (export "update" (func $lower-update))
    (export "draw" (func $lower-draw))
    (export "memory" (memory $memory)))
  (core instance $run (instantiate $code (with "host" (instance $host))))
  (func (export "init") (canon lift (core func $run "init")))
  (func (export "frame") (canon lift (core func $run "frame"))))
