// Generated by tools/bridgegen/generate.py; edit data/contract.json.

/// Largest game and session frame payload in bytes.
pub const MAX_FRAME_LEN: usize = 67108864;

/// Largest control request or response payload in bytes.
pub(crate) const CONTROL_MAX_FRAME_LEN: usize = 65536;

/// Most server addresses admitted in one ping request.
pub(crate) const MAX_PING_TARGETS: usize = 64;

/// Client session setup carrying JSON login data.
pub(crate) const KIND_CONNECT: u8 = 1;

/// A batch of length-prefixed packets in either direction.
pub(crate) const KIND_BATCH: u8 = 2;

/// Core handoff containing JSON and startup packets.
pub(crate) const KIND_HANDOFF: u8 = 3;

/// Core resource-pack index followed by archive bytes.
pub(crate) const KIND_PACK_DATA: u8 = 4;

/// Terminal core transfer message.
pub(crate) const KIND_TRANSFER: u8 = 5;

/// Terminal core disconnect message.
pub(crate) const KIND_DISCONNECT: u8 = 6;
