use std::path::Path;

use bytes::Bytes;
use futures::{SinkExt, StreamExt};
use serde::{Deserialize, Serialize};

use crate::contract::CONTROL_MAX_FRAME_LEN;
use crate::endpoint::EndpointKind;
use crate::status::{RpcError, invalid};
use crate::{BridgeError, FramedStream};

const WORLD_REQUEST_ID: u64 = 1;
const WORLD_SCHEMA_VERSION: u32 = 1;

/// Game mode a world starts players in.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum GameMode {
    #[default]
    Survival,
    Creative,
    Adventure,
}

/// Terrain generator of a local world.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Generator {
    /// Natural terrain generated by the selected backend.
    #[default]
    Normal,
    Flat,
}

/// Difficulty of a local world.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Difficulty {
    Peaceful,
    Easy,
    #[default]
    Normal,
    Hard,
}

/// Server backend a world runs on; fixed when the world is created.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Backend {
    /// Bedrock Dedicated Server: vanilla terrain and mobs.
    Bds,
    /// Built-in Dragonfly server with flat or natural terrain.
    #[default]
    Dragonfly,
}

/// One saved local world as listed by the core.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct World {
    pub id: String,
    pub name: String,
    pub game_mode: GameMode,
    pub generator: Generator,
    pub difficulty: Difficulty,
    #[serde(default)]
    pub backend: Backend,
    pub seed: i64,
    pub created_unix: i64,
    pub last_played_unix: i64,
    /// Bytes on disk.
    #[serde(default)]
    pub size_bytes: u64,
}

/// Settings changes for a saved world; `None` fields are left alone.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
pub struct WorldUpdate {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub game_mode: Option<GameMode>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub difficulty: Option<Difficulty>,
}

/// Settings for a new world; a `None` seed is chosen randomly by the core.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
pub struct NewWorld {
    pub name: String,
    pub game_mode: GameMode,
    pub generator: Generator,
    pub difficulty: Difficulty,
    /// `None` takes the core's default for this machine.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backend: Option<Backend>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,
}

/// Lifecycle of the open local world.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum WorldState {
    Idle,
    Starting,
    Running,
    Stopping,
    Failed,
}

/// Why the dedicated-server backend cannot run.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum UnavailableReason {
    DockerMissing,
    DockerNotRunning,
    #[serde(other)]
    Other,
}

/// Dedicated-server acquisition progress.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SetupState {
    Unsupported,
    EulaRequired,
    NotInstalled,
    /// Container runtime: probing the Docker daemon at open.
    CheckingRuntime,
    /// Container runtime: pulling the server image (layer counts only).
    PullingImage,
    Downloading,
    Unpacking,
    Ready,
    Failed,
    #[serde(other)]
    Other,
}

/// Dedicated-server setup as reported in [`WorldStatus`].
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct Setup {
    pub state: SetupState,
    #[serde(default)]
    pub version: Option<String>,
    #[serde(default)]
    pub bytes_done: u64,
    #[serde(default)]
    pub bytes_total: u64,
    #[serde(default)]
    pub layers_done: u32,
    #[serde(default)]
    pub layers_total: u32,
    #[serde(default)]
    pub eula_accepted: bool,
    #[serde(default)]
    pub error: Option<String>,
    /// `native`, `container` or `none`.
    #[serde(default)]
    pub runtime: String,
    #[serde(default)]
    pub reason: Option<String>,
}

/// Status of the open local world; `error` is a short reason with no local paths.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct WorldStatus {
    pub state: WorldState,
    #[serde(default)]
    pub world_id: Option<String>,
    /// Backend of the open world.
    #[serde(default)]
    pub backend: Option<Backend>,
    #[serde(default)]
    pub paused: bool,
    /// False when the open world's server cannot pause (BDS).
    #[serde(default)]
    pub pause_supported: bool,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub setup: Option<Setup>,
    #[serde(default)]
    pub backend_unavailable_reason: Option<UnavailableReason>,
    /// The running server's player limit, the host included.
    #[serde(default)]
    pub max_players: Option<u32>,
}

/// Local-world preferences kept by the core.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq)]
pub struct Prefs {
    #[serde(default)]
    pub docker_prompt_dismissed: bool,
}

/// Changes to [`Prefs`]; `redetect` re-probes for Docker before the core replies.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize)]
pub struct PrefsUpdate {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub docker_prompt_dismissed: Option<bool>,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub redetect: bool,
}

#[derive(Serialize)]
struct WorldRequest<'a, P: Serialize> {
    jsonrpc: &'static str,
    id: u64,
    method: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    params: Option<P>,
}

#[derive(Deserialize)]
struct WorldResponse {
    jsonrpc: String,
    id: u64,
    #[serde(default)]
    result: Option<WorldResult>,
    #[serde(default)]
    error: Option<RpcError>,
}

#[derive(Default, Deserialize)]
struct WorldResult {
    schema_version: u32,
    #[serde(default)]
    worlds: Vec<World>,
    #[serde(default)]
    world: Option<World>,
    #[serde(default)]
    status: Option<WorldStatus>,
    #[serde(default)]
    prefs: Option<Prefs>,
}

#[derive(Serialize)]
struct IdParams<'a> {
    id: &'a str,
}

#[derive(Serialize)]
struct UpdateParams<'a> {
    id: &'a str,
    #[serde(flatten)]
    update: &'a WorldUpdate,
}

#[derive(Serialize)]
struct OpenParams<'a> {
    id: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    view_distance: Option<u32>,
}

#[derive(Serialize)]
struct EulaParams {
    accepted: bool,
}

#[derive(Serialize)]
struct PauseParams {
    paused: bool,
}

#[derive(Serialize)]
struct InviteParams<'a> {
    xuid: &'a str,
}

async fn call<P: Serialize>(
    socket_dir: &Path,
    method: &str,
    params: Option<P>,
) -> Result<WorldResult, BridgeError> {
    let stream = crate::endpoint::connect(socket_dir, EndpointKind::Control).await?;
    let mut framed = FramedStream::with_max(stream, CONTROL_MAX_FRAME_LEN);
    let request = serde_json::to_vec(&WorldRequest {
        jsonrpc: "2.0",
        id: WORLD_REQUEST_ID,
        method,
        params,
    })?;
    framed.send(Bytes::from(request)).await?;
    let response = framed.next().await.ok_or(BridgeError::ControlClosed)??;
    parse_world_response(&response)
}

fn parse_world_response(payload: &[u8]) -> Result<WorldResult, BridgeError> {
    let response: WorldResponse = serde_json::from_slice(payload)?;
    if response.jsonrpc != "2.0" {
        return invalid("jsonrpc must be exactly 2.0");
    }
    if response.id != WORLD_REQUEST_ID {
        return invalid("response id does not match the request");
    }
    match (response.result, response.error) {
        (Some(result), None) => {
            if result.schema_version != WORLD_SCHEMA_VERSION {
                return invalid("unsupported world schema version");
            }
            Ok(result)
        }
        (None, Some(error)) => Err(BridgeError::ControlRpc {
            code: error.code,
            message: error.message,
        }),
        (Some(_), Some(_)) => invalid("response contains both result and error"),
        (None, None) => invalid("response contains neither result nor error"),
    }
}

fn require_world(result: WorldResult) -> Result<World, BridgeError> {
    result
        .world
        .map_or_else(|| invalid("response is missing the world"), Ok)
}

fn require_status(result: WorldResult) -> Result<WorldStatus, BridgeError> {
    result
        .status
        .map_or_else(|| invalid("response is missing the world status"), Ok)
}

/// Lists saved worlds, most recently played first.
pub async fn list_worlds(socket_dir: &Path) -> Result<Vec<World>, BridgeError> {
    Ok(call::<()>(socket_dir, "world_list.v1", None).await?.worlds)
}

/// Creates a world and returns its saved metadata.
pub async fn create_world(socket_dir: &Path, world: &NewWorld) -> Result<World, BridgeError> {
    require_world(call(socket_dir, "world_create.v1", Some(world)).await?)
}

/// Changes a world's name, game mode or difficulty; the latter two apply on its next open.
pub async fn update_world(
    socket_dir: &Path,
    id: &str,
    update: &WorldUpdate,
) -> Result<World, BridgeError> {
    require_world(
        call(
            socket_dir,
            "world_update.v1",
            Some(UpdateParams { id, update }),
        )
        .await?,
    )
}

/// Deletes a world that is not open.
pub async fn delete_world(socket_dir: &Path, id: &str) -> Result<(), BridgeError> {
    call(socket_dir, "world_delete.v1", Some(IdParams { id })).await?;
    Ok(())
}

/// Starts opening a world; poll [`world_status`] until it is running, then connect the game socket.
pub async fn open_world(socket_dir: &Path, id: &str) -> Result<WorldStatus, BridgeError> {
    open_world_with(socket_dir, id, None).await
}

/// [`open_world`] with the client's view distance in chunks. An RPC error with code
/// [`CODE_EULA_REQUIRED`] means the user must accept the Minecraft EULA first.
pub async fn open_world_with(
    socket_dir: &Path,
    id: &str,
    view_distance: Option<u32>,
) -> Result<WorldStatus, BridgeError> {
    let params = OpenParams { id, view_distance };
    require_status(call(socket_dir, "world_open.v1", Some(params)).await?)
}

/// RPC error code of an open that needs the EULA accepted first.
pub const CODE_EULA_REQUIRED: i64 = -32012;

/// Records the user's explicit acceptance of the Minecraft EULA for the dedicated server download.
pub async fn accept_bds_eula(socket_dir: &Path) -> Result<WorldStatus, BridgeError> {
    let params = EulaParams { accepted: true };
    require_status(call(socket_dir, "bds_accept_eula.v1", Some(params)).await?)
}

/// Reads or updates local-world preferences and returns them with the current status.
pub async fn local_worlds_prefs(
    socket_dir: &Path,
    update: &PrefsUpdate,
) -> Result<(Prefs, WorldStatus), BridgeError> {
    let params = (*update != PrefsUpdate::default()).then_some(update);
    let result = call(socket_dir, "local_worlds_prefs.v1", params).await?;
    let prefs = result
        .prefs
        .map_or_else(|| invalid("response is missing the preferences"), Ok)?;
    Ok((prefs, require_status(result)?))
}

/// Saves and stops the open world, or clears a failed open.
pub async fn close_world(socket_dir: &Path) -> Result<WorldStatus, BridgeError> {
    require_status(call::<()>(socket_dir, "world_close.v1", None).await?)
}

/// Freezes or resumes the open world (window focus loss and regain).
pub async fn set_world_paused(socket_dir: &Path, paused: bool) -> Result<WorldStatus, BridgeError> {
    require_status(call(socket_dir, "world_pause.v1", Some(PauseParams { paused })).await?)
}

/// Reads the open world's lifecycle.
pub async fn world_status(socket_dir: &Path) -> Result<WorldStatus, BridgeError> {
    require_status(call::<()>(socket_dir, "world_status.v1", None).await?)
}

/// Sends the Xbox friend `xuid` an invite to the open world; the core refuses it while no
/// world is hosted for friends.
pub async fn invite_to_world(socket_dir: &Path, xuid: &str) -> Result<(), BridgeError> {
    call(socket_dir, "world_invite.v1", Some(InviteParams { xuid })).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn requests_match_the_wire_contract() {
        let params = serde_json::to_value(&WorldRequest {
            jsonrpc: "2.0",
            id: 1,
            method: "world_open.v1",
            params: Some(IdParams { id: "ab" }),
        })
        .expect("encode");
        assert_eq!(
            params,
            serde_json::json!({"jsonrpc":"2.0","id":1,"method":"world_open.v1","params":{"id":"ab"}})
        );
        let bare = serde_json::to_value(&WorldRequest::<()> {
            jsonrpc: "2.0",
            id: 1,
            method: "world_list.v1",
            params: None,
        })
        .expect("encode");
        assert_eq!(
            bare,
            serde_json::json!({"jsonrpc":"2.0","id":1,"method":"world_list.v1"})
        );
    }

    #[test]
    fn invite_params_name_the_friend() {
        let invite = serde_json::to_value(&WorldRequest {
            jsonrpc: "2.0",
            id: 1,
            method: "world_invite.v1",
            params: Some(InviteParams {
                xuid: "2535400000000001",
            }),
        })
        .expect("encode");
        assert_eq!(
            invite["params"],
            serde_json::json!({"xuid": "2535400000000001"})
        );
    }

    #[test]
    fn new_world_omits_random_seed_and_keeps_zero() {
        let random = serde_json::to_value(&NewWorld {
            name: "a".into(),
            ..NewWorld::default()
        })
        .expect("encode");
        assert_eq!(
            random,
            serde_json::json!({"name":"a","game_mode":"survival","generator":"normal","difficulty":"normal"})
        );
        let zero = serde_json::to_value(&NewWorld {
            name: "a".into(),
            seed: Some(0),
            ..NewWorld::default()
        })
        .expect("encode");
        assert_eq!(zero.get("seed"), Some(&serde_json::json!(0)));
    }

    #[test]
    fn parses_list_and_status_results() {
        let list = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,"worlds":[
            {"id":"0123456789abcdef","name":"One","game_mode":"creative","generator":"flat",
             "difficulty":"hard","seed":-5,"created_unix":10,"last_played_unix":20}]}}"#;
        let worlds = parse_world_response(list).expect("list").worlds;
        assert_eq!(worlds.len(), 1);
        assert_eq!(worlds[0].game_mode, GameMode::Creative);
        assert_eq!(worlds[0].seed, -5);
        let status = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,
            "status":{"state":"starting","world_id":"x","paused":false}}}"#;
        let status = require_status(parse_world_response(status).expect("status")).expect("status");
        assert_eq!(status.state, WorldState::Starting);
        assert_eq!(status.world_id.as_deref(), Some("x"));
    }

    #[test]
    fn parses_backend_setup_and_unavailable_reason() {
        let raw = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,"prefs":{"docker_prompt_dismissed":true},
            "status":{"state":"idle","pause_supported":true,"backend_unavailable_reason":"docker_missing",
            "setup":{"state":"unsupported","runtime":"none","reason":"no docker"}}}}"#;
        let result = parse_world_response(raw).expect("status");
        assert_eq!(
            result.prefs,
            Some(Prefs {
                docker_prompt_dismissed: true
            })
        );
        let status = require_status(result).expect("status");
        assert_eq!(
            status.backend_unavailable_reason,
            Some(UnavailableReason::DockerMissing)
        );
        assert_eq!(status.setup.expect("setup").state, SetupState::Unsupported);
        let pulling = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,
            "status":{"state":"starting","setup":{"state":"pulling_image","layers_done":2,"layers_total":5}}}}"#;
        let setup = require_status(parse_world_response(pulling).expect("ok"))
            .expect("status")
            .setup
            .expect("setup");
        assert_eq!(
            (setup.state, setup.layers_done, setup.layers_total),
            (SetupState::PullingImage, 2, 5)
        );
        let future = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,
            "status":{"state":"starting","setup":{"state":"verifying"}}}}"#;
        let setup = require_status(parse_world_response(future).expect("ok"))
            .expect("status")
            .setup
            .expect("setup");
        assert_eq!(setup.state, SetupState::Other);
        let unknown = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,
            "status":{"state":"idle","backend_unavailable_reason":"something_new"}}}"#;
        let status = require_status(parse_world_response(unknown).expect("ok")).expect("status");
        assert_eq!(
            status.backend_unavailable_reason,
            Some(UnavailableReason::Other)
        );
    }

    #[test]
    fn worlds_without_backend_default_to_dragonfly_and_requests_encode() {
        let list = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":1,"worlds":[
            {"id":"a","name":"n","game_mode":"survival","generator":"normal","difficulty":"normal",
             "seed":1,"created_unix":0,"last_played_unix":0}]}}"#;
        assert_eq!(
            parse_world_response(list).expect("list").worlds[0].backend,
            Backend::Dragonfly
        );
        let open = serde_json::to_value(&OpenParams {
            id: "a",
            view_distance: Some(12),
        })
        .expect("encode");
        assert_eq!(open, serde_json::json!({"id":"a","view_distance":12}));
        let prefs = serde_json::to_value(PrefsUpdate {
            docker_prompt_dismissed: Some(true),
            redetect: true,
        })
        .expect("encode");
        assert_eq!(
            prefs,
            serde_json::json!({"docker_prompt_dismissed":true,"redetect":true})
        );
        let empty = serde_json::to_value(PrefsUpdate::default()).expect("encode");
        assert_eq!(empty, serde_json::json!({}));
        let eula = serde_json::to_value(&EulaParams { accepted: true }).expect("encode");
        assert_eq!(eula, serde_json::json!({"accepted":true}));
        let update = serde_json::to_value(&UpdateParams {
            id: "a",
            update: &WorldUpdate {
                difficulty: Some(Difficulty::Hard),
                ..WorldUpdate::default()
            },
        })
        .expect("encode");
        assert_eq!(update, serde_json::json!({"id":"a","difficulty":"hard"}));
    }

    #[test]
    fn surfaces_rpc_errors_and_rejects_bad_envelopes() {
        let error =
            br#"{"jsonrpc":"2.0","id":1,"error":{"code":-32010,"message":"world not found"}}"#;
        assert!(matches!(
            parse_world_response(error),
            Err(BridgeError::ControlRpc { code: -32010, .. })
        ));
        let wrong_schema = br#"{"jsonrpc":"2.0","id":1,"result":{"schema_version":2}}"#;
        assert!(parse_world_response(wrong_schema).is_err());
        let wrong_id = br#"{"jsonrpc":"2.0","id":9,"result":{"schema_version":1}}"#;
        assert!(parse_world_response(wrong_id).is_err());
        let missing = require_world(WorldResult {
            schema_version: 1,
            ..WorldResult::default()
        });
        assert!(missing.is_err());
    }
}
