[package]
name = "mod-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
mod-api = { path = "../mod-api" }
naga = { version = "30.0.1", features = ["wgsl-in"] }

[lints]
workspace = true
