[package]
name = "meshing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
assets = { path = "../assets" }
bytemuck = { version = "1", features = ["derive"] }
world = { path = "../world" }

[dev-dependencies]
pack-compiler = { path = "../pack-compiler" }
image.workspace = true
serde_json = "1"
tempfile = "3"
