// Command blockdestroy joins pinned block-data sources into the block destroy table.
//
// Hardness comes from the shared block-state catalog. Tool and harvest
// classes remain provisional PrismarineJS evidence; rows without that evidence
// are unresolved so the client does not assume the hand harvests them.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	shared "github.com/bedrock-mc/protocolgen/generated/data"
	sharedblock "github.com/bedrock-mc/protocolgen/generated/data/block"
)

const (
	prismarineSourceID = "prismarinejs-minecraft-data"
	prismarineFile     = "blocks.json"
	maximumInputBytes  = 8 << 20
)

type manifest struct {
	Protocol struct {
		GameVersion string `json:"game_version"`
	} `json:"protocol"`
	Sources []struct {
		ID          string `json:"id"`
		Commit      string `json:"commit"`
		Destination string `json:"destination"`
		Files       []struct {
			InstallPath string `json:"install_path"`
			SHA256      string `json:"sha256"`
		} `json:"files"`
	} `json:"sources"`
}

type pinnedFile struct {
	path   string
	sha256 string
	commit string
}

// Harvest families by PrismarineJS item id; the value is the tool's harvest level.
var harvestFamilies = map[int]struct {
	tool  string
	level int
}{
	941: {"pickaxe", 0}, 946: {"pickaxe", 1}, 951: {"pickaxe", 1}, 956: {"pickaxe", 0},
	961: {"pickaxe", 2}, 966: {"pickaxe", 3}, 971: {"pickaxe", 4},
	940: {"shovel", 0}, 945: {"shovel", 1}, 950: {"shovel", 1}, 955: {"shovel", 0},
	960: {"shovel", 2}, 965: {"shovel", 3}, 970: {"shovel", 4},
	939: {"sword", 0}, 944: {"sword", 1}, 949: {"sword", 1}, 954: {"sword", 0},
	959: {"sword", 2}, 964: {"sword", 3}, 969: {"sword", 4},
	1134: {"shears", 0},
}

var materialTools = map[string][]string{
	"mineable/pickaxe":      {"pickaxe"},
	"mineable/axe":          {"axe"},
	"mineable/shovel":       {"shovel"},
	"mineable/hoe":          {"hoe"},
	"leaves":                {"shears"},
	"coweb":                 {"sword", "shears"},
	"wool":                  {"shears"},
	"sword_instantly_mines": {"sword"},
}

// Materials whose tool effectiveness may not carry over to Bedrock; they contribute none.
var unverifiedMaterials = map[string]bool{"plant": true, "vine_or_glow_lichen": true}

type prismarineBlock struct {
	Name         string          `json:"name"`
	Material     string          `json:"material"`
	HarvestTools map[string]bool `json:"harvestTools"`
}

type row struct {
	identifier   string
	hardness     float32
	effective    []string
	harvestTools []string
	harvestLevel int // -1 when no tool is required for drops
	unresolved   bool
}

func main() {
	manifestPath := flag.String("manifest", "", "pinned block-data source manifest")
	bundle := flag.String("bundle", "", "installed local-only block-data bundle")
	output := flag.String("out", "", "generated destroy table")
	flag.Parse()
	if err := run(*manifestPath, *bundle, *output); err != nil {
		fmt.Fprintln(os.Stderr, "blockdestroy:", err)
		os.Exit(1)
	}
}

func run(manifestPath, bundle, output string) error {
	if manifestPath == "" || bundle == "" || output == "" {
		return errors.New("-manifest, -bundle and -out are required")
	}
	data, err := readBounded(manifestPath)
	if err != nil {
		return err
	}
	var pinned manifest
	if err := json.Unmarshal(data, &pinned); err != nil {
		return fmt.Errorf("decode manifest: %w", err)
	}
	prismarine, err := locate(pinned, bundle, prismarineSourceID, prismarineFile)
	if err != nil {
		return err
	}
	prismarineBytes, err := readPinned(prismarine)
	if err != nil {
		return err
	}
	hardness, err := sharedHardness()
	if err != nil {
		return err
	}
	rows, err := build(hardness, prismarineBytes)
	if err != nil {
		return err
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "# Generated by tools/registrygen/cmd/blockdestroy for %s; do not edit.\n", shared.MinecraftVersion)
	fmt.Fprintf(&out, "# hardness: protocolgen/generated/data source_lock_sha256=%s\n", shared.SourceLockSHA256)
	fmt.Fprintf(&out, "# tools (provisional): %s@%s %s sha256=%s\n", prismarineSourceID, prismarine.commit, prismarineFile, prismarine.sha256)
	out.WriteString("# identifier\thardness\teffective_tools\tharvest_tools\tharvest_level\n")
	for _, r := range rows {
		effective, harvest, level := list(r.effective), list(r.harvestTools), "-"
		if r.harvestLevel >= 0 {
			level = strconv.Itoa(r.harvestLevel)
		}
		if r.unresolved {
			effective, harvest, level = "?", "?", "?"
		}
		fmt.Fprintf(&out, "%s\t%s\t%s\t%s\t%s\n", r.identifier,
			strconv.FormatFloat(float64(r.hardness), 'g', -1, 32), effective, harvest, level)
	}
	return os.WriteFile(output, out.Bytes(), 0o644)
}

func locate(pinned manifest, bundle, id, file string) (pinnedFile, error) {
	for _, source := range pinned.Sources {
		if source.ID != id {
			continue
		}
		for _, entry := range source.Files {
			if entry.InstallPath == file {
				return pinnedFile{
					path:   filepath.Join(bundle, source.Destination, entry.InstallPath),
					sha256: entry.SHA256,
					commit: source.Commit,
				}, nil
			}
		}
	}
	return pinnedFile{}, fmt.Errorf("manifest pins no %s file %s", id, file)
}

func readPinned(file pinnedFile) ([]byte, error) {
	data, err := readBounded(file.path)
	if err != nil {
		return nil, err
	}
	digest := sha256.Sum256(data)
	if actual := hex.EncodeToString(digest[:]); actual != file.sha256 {
		return nil, fmt.Errorf("%s: SHA-256 mismatch: expected %s, got %s", file.path, file.sha256, actual)
	}
	return data, nil
}

func readBounded(path string) ([]byte, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	data, err := io.ReadAll(io.LimitReader(file, maximumInputBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if len(data) > maximumInputBytes {
		return nil, fmt.Errorf("%s exceeds %d bytes", path, maximumInputBytes)
	}
	return data, nil
}

// sharedHardness requires one hardness per identifier because this client table has no state key.
func sharedHardness() (map[string]float32, error) {
	values := make(map[string]float32)
	for i := 0; i < sharedblock.StateCount(); i++ {
		state, _ := sharedblock.StateAt(i)
		block, _ := sharedblock.BlockAt(state.Block)
		properties, _ := sharedblock.PropertiesAt(state.Properties)
		if previous, ok := values[block.Name]; ok && previous != properties.Hardness {
			return nil, fmt.Errorf("%s has state-dependent hardness; destroy table needs a state key", block.Name)
		}
		values[block.Name] = properties.Hardness
	}
	return values, nil
}

// build joins shared hardness to the independently pinned tool classification evidence.
func build(properties map[string]float32, prismarineBytes []byte) ([]row, error) {
	var blocks []prismarineBlock
	if err := json.Unmarshal(prismarineBytes, &blocks); err != nil {
		return nil, fmt.Errorf("decode %s: %w", prismarineFile, err)
	}
	byName := make(map[string]prismarineBlock, len(blocks))
	for _, block := range blocks {
		byName["minecraft:"+block.Name] = block
	}
	rows := make([]row, 0, len(properties))
	for identifier, property := range properties {
		r := row{identifier: identifier, hardness: property, harvestLevel: -1}
		if block, ok := byName[identifier]; ok {
			var err error
			if r.effective, r.harvestTools, r.harvestLevel, err = classify(block); err != nil {
				return nil, fmt.Errorf("%s: %w", identifier, err)
			}
		}
		r.unresolved = len(r.effective) == 0 && len(r.harvestTools) == 0
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].identifier < rows[j].identifier })
	return rows, nil
}

func classify(block prismarineBlock) (effective, harvest []string, level int, err error) {
	tools := map[string]bool{}
	parts := strings.Split(block.Material, ";")
	for _, part := range parts {
		if unverifiedMaterials[part] {
			parts = nil
			break
		}
	}
	for _, part := range parts {
		for _, tool := range materialTools[part] {
			tools[tool] = true
		}
	}
	harvestSet := map[string]bool{}
	level = -1
	for id := range block.HarvestTools {
		number, parseErr := strconv.Atoi(id)
		if parseErr != nil {
			return nil, nil, 0, fmt.Errorf("harvest tool id %q: %w", id, parseErr)
		}
		family, ok := harvestFamilies[number]
		if !ok {
			return nil, nil, 0, fmt.Errorf("unclassified harvest tool id %d", number)
		}
		tools[family.tool] = true
		harvestSet[family.tool] = true
		if level < 0 || family.level < level {
			level = family.level
		}
	}
	return keys(tools), keys(harvestSet), level, nil
}

func keys(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for key := range set {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

func list(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	return strings.Join(values, ",")
}
