// Command blockdestroy joins shared block hardness and provisional mining facts.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	shared "github.com/bedrock-mc/protocolgen/generated/data"
	sharedblock "github.com/bedrock-mc/protocolgen/generated/data/block"
)

type row struct {
	identifier   string
	hardness     float32
	effective    []string
	harvestTools []string
	harvestLevel int // -1 when no tool is required for drops
	unresolved   bool
}

func main() {
	output := flag.String("out", "", "generated destroy table")
	flag.Parse()
	if err := run(*output); err != nil {
		fmt.Fprintln(os.Stderr, "blockdestroy:", err)
		os.Exit(1)
	}
}

// run writes the destroy table from one shared release catalog.
func run(output string) error {
	if output == "" {
		return errors.New("-out is required")
	}
	if sharedblock.MiningSourceLockSHA256 != shared.SourceLockSHA256 {
		return errors.New("shared mining facts and block properties use different source locks")
	}
	hardness, err := sharedHardness()
	if err != nil {
		return err
	}
	rows := build(hardness)
	var out bytes.Buffer
	fmt.Fprintf(&out, "# Generated by tools/registrygen/cmd/blockdestroy for %s; do not edit.\n", shared.MinecraftVersion)
	fmt.Fprintf(&out, "# hardness and tools: protocolgen/generated/data source_lock_sha256=%s\n", shared.SourceLockSHA256)
	fmt.Fprintf(&out, "# tools (provisional): PrismarineJS Bedrock %s@%s blocks.json sha256=%s\n", sharedblock.MiningEvidenceVersion, sharedblock.MiningEvidenceRevision, sharedblock.MiningEvidenceSHA256)
	out.WriteString("# identifier\thardness\teffective_tools\tharvest_tools\tharvest_level\n")
	for _, r := range rows {
		effective, harvest, level := list(r.effective), list(r.harvestTools), "-"
		if r.harvestLevel >= 0 {
			level = strconv.Itoa(r.harvestLevel)
		}
		if r.unresolved {
			effective, harvest, level = "?", "?", "?"
		}
		fmt.Fprintf(&out, "%s\t%s\t%s\t%s\t%s\n", r.identifier,
			strconv.FormatFloat(float64(r.hardness), 'g', -1, 32), effective, harvest, level)
	}
	return os.WriteFile(output, out.Bytes(), 0o644)
}

// sharedHardness requires one hardness per identifier because this client table has no state key.
func sharedHardness() (map[string]float32, error) {
	values := make(map[string]float32)
	for i := 0; i < sharedblock.StateCount(); i++ {
		state, _ := sharedblock.StateAt(i)
		block, _ := sharedblock.BlockAt(state.Block)
		properties, _ := sharedblock.PropertiesAt(state.Properties)
		if previous, ok := values[block.Name]; ok && previous != properties.Hardness {
			return nil, fmt.Errorf("%s has state-dependent hardness; destroy table needs a state key", block.Name)
		}
		values[block.Name] = properties.Hardness
	}
	return values, nil
}

// build joins shared hardness to shared provisional tool classifications.
func build(properties map[string]float32) []row {
	rows := make([]row, 0, len(properties))
	for identifier, hardness := range properties {
		r := row{identifier: identifier, hardness: hardness, harvestLevel: -1}
		if facts, ok := sharedblock.MiningByName(identifier); ok {
			r.effective = families(facts.EffectiveTools)
			r.harvestTools = families(facts.HarvestTools)
			r.harvestLevel = int(facts.HarvestLevel)
		} else {
			r.unresolved = true
		}
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].identifier < rows[j].identifier })
	return rows
}

// families lists a generated tool-family set in stable name order.
func families(set sharedblock.ToolFamilies) []string {
	var names []string
	for _, tool := range []struct {
		mask sharedblock.ToolFamilies
		name string
	}{
		{sharedblock.ToolPickaxe, "pickaxe"},
		{sharedblock.ToolAxe, "axe"},
		{sharedblock.ToolShovel, "shovel"},
		{sharedblock.ToolHoe, "hoe"},
		{sharedblock.ToolSword, "sword"},
		{sharedblock.ToolShears, "shears"},
	} {
		if set.Has(tool.mask) {
			names = append(names, tool.name)
		}
	}
	sort.Strings(names)
	return names
}

// list encodes an empty tool-family set as a dash in the table.
func list(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	return strings.Join(values, ",")
}
