//! Shared production commit-to-input authority registrations.
use super::*;
use crate::runtime::world::{advance_dimension_transfer, drain_committed_ui_before_authority};

pub(crate) fn configure_client_frame_schedule(app: &mut App) {
    app.configure_sets(
        Update,
        (
            ClientFrameSet::RawInput,
            ClientFrameSet::SemanticSample,
            ClientFrameSet::UiAuthority,
            ClientFrameSet::SemanticFinalize,
            ClientFrameSet::Physics,
            ClientFrameSet::Camera,
            ClientFrameSet::Interaction,
            // Packets leave before world, actor and UI preparation, as vanilla flushes before render.
            ClientFrameSet::NetworkSend,
            ClientFrameSet::WorldPublication,
            ClientFrameSet::ActorPreparation,
            ClientFrameSet::UiPreparation,
            ClientFrameSet::ActorFinalization,
            ClientFrameSet::ActorPublication,
            ClientFrameSet::UiPublication,
        )
            .chain(),
    );
}

pub(crate) fn configure_client_authority_systems(app: &mut App) {
    app.add_plugins(client_presentation::ClientPresentationPlugin)
        .add_message::<client_presentation::audio_ingress::SequencedAudioEvent>()
        .add_message::<bevy::input::mouse::MouseWheel>()
        .init_resource::<WorldStreamFramePoll>()
        .init_resource::<client_ui::ui_runtime::presentation::PreparedUiPublication>()
        .init_resource::<crate::ui_runtime::emotes::EmoteInputConsumed>()
        .add_systems(
            Update,
            (drive_gameplay_touch_targets, collect_raw_input)
                .chain()
                .in_set(ClientFrameSet::RawInput),
        )
        .add_systems(
            Update,
            route_semantic_input.in_set(ClientFrameSet::SemanticSample),
        )
        .add_systems(
            Update,
            (
                crate::ui_runtime::scene_stack::close_scenes_on_player_hurt,
                drive_sign_editor.run_if(crate::server_experiences::input::ordinary_input),
                drive_server_form_input.run_if(crate::server_experiences::input::ordinary_input),
                crate::ui_runtime::emotes::drive_emote_input,
                drive_chat_ui_actions.run_if(crate::server_experiences::input::ordinary_input),
                drain_inventory_authority,
                drive_chat_keyboard_input.run_if(crate::server_experiences::input::ordinary_input),
                crate::fullscreen::toggle_fullscreen_hotkey,
                drive_menu_input,
                crate::fullscreen::apply_runtime_fullscreen_setting,
                crate::ui_runtime::presentation::apply_gui_scale_setting,
                crate::menu::persist_video_settings,
                (
                    drive_inventory_ui_actions
                        .run_if(crate::server_experiences::input::ordinary_input),
                    apply_deferred_inventory_close,
                )
                    .chain(),
                drive_menu_services,
                drive_session,
                crate::settings_runtime::apply_window_settings,
                crate::settings_runtime::apply_render_distance,
                crate::store::drive_store,
                synchronize_semantic_input_authority,
                drive_world_inventory_keys.run_if(crate::server_experiences::input::ordinary_input),
            )
                .chain()
                .in_set(ClientFrameSet::UiAuthority),
        )
        .add_systems(
            Update,
            (
                finalize_semantic_input_after_ui_authority,
                crate::ui_runtime::emotes::cancel_emote_from_gameplay,
            )
                .chain()
                .in_set(ClientFrameSet::SemanticFinalize),
        )
        .add_systems(
            Update,
            reconcile_world_stream_before_physics
                .after(receive_network_events)
                .before(drain_committed_ui_before_authority)
                .before(ClientFrameSet::UiAuthority)
                .before(ClientFrameSet::Physics),
        )
        .add_systems(
            Update,
            advance_dimension_transfer
                .after(reconcile_world_stream_before_physics)
                .after(ClientFrameSet::UiAuthority)
                .before(ClientFrameSet::Physics),
        )
        .add_systems(
            Update,
            drain_committed_ui_before_authority
                .after(reconcile_world_stream_before_physics)
                .before(ClientFrameSet::UiAuthority),
        );
}
